### ISSUE TITLE
Recommended barcode scanner package

### ISSUE THREAD

**Issue by benpretorius** [marcus-bornman/rsa_identification#1]
Hi there,

Which futter barcode scanner package have you successfully been able to implement with this?
I'm using firebase ml, but I'm having trouble converting the rawValue of the barcode into bytes.
Any suggestion would be much appreciated :)

**Comment by the-mars-rover** [comment]
Hi @benpretorius,

So I couldn't actually find a barcode scanner which provides the raw bytes. However, what I did was:
1. fork from the ml_vision
2. implement the property to provide raw bytes
3. reference my customised package locally

I know this is not ideal, so I reported [an issue](https://github.com/FirebaseExtended/flutterfire/issues/1816) with the ml_vision package and submitted [a PR](https://github.com/FirebaseExtended/flutterfire/pull/1820/) for that issue. Unfortunately the PR has not been merged. If you would be so kind, please also leave a 👍 on [the issue](https://github.com/FirebaseExtended/flutterfire/issues/1816) and on [the PR](https://github.com/FirebaseExtended/flutterfire/pull/1820/) - maybe even leave a comment on the issue noting urgency...hopefully this will get them to merge it sooner rather than later, in which case we can all use the ml_vision package out of the box :)

**Comment by benpretorius** [comment]
Hi @marcus-bornman ,

OK great thanks a lot for the library, and all your effort regarding this. I'll definitely go and upvote the PR and leave a comment. Will also share with other flutter devs I know :)
